@host = http://localhost:3000
@baseUrl = {{host}}/api/v1
@contenType = application/json

POST {{baseUrl}}/books
Content-Type: {{contenType}}

{
    "title": "O Senhor dos Anéis",
    "subtitle": "A Sociedade do Anel",
    "author": "J.R.R. Tolkien",
    "genre": "Fantasia",
    "cover": "https://harpercollins.com.br/cdn/shop/products/9786555113631_79a81e4f-07c1-4aa8-ba58-b44033442bbf.jpg"
    }