@host = http://localhost:3000
@baseUrl = {{host}}/api/v1
@contenType = application/json

POST {{baseUrl}}/books
Content-Type: {{contenType}}

{
  "title": "O Senhor dos Anéis",
  "subtitle": "A Sociedade do Anel",
  "author": "J.R.R. Tolkien",
  "genre": "Fantasia",
  "cover": "https://harpercollins.com.br/cdn/shop/products/9786555113631_79a81e4f-07c1-4aa8-ba58-b44033442bbf.jpg"
}

###
GET {{baseUrl}}/books
Content-Type: {{contenType}}

###
GET {{baseUrl}}/books/66b39cc014aad28835d656ff
Content-Type: {{contenType}}

###
PUT {{baseUrl}}/books/66b39cc014aad28835d656ff
Content-Type: {{contenType}}

{
  "subtitle": "As Duas Torres",
  "cover": "https://harpercollins.com.br/cdn/shop/products/9786555113624_84e92bc9-fe5b-4d2c-9c79-5d2153540499.jpg"
}